(cl:in-package #:parcl)

(defmethod find-symbol (client package name)
  (multiple-value-bind (symbol status)
      (find-present-symbol client package name)
    (if (not (null status))
        (values symbol status)
        (loop for used-package in (use-list client package)
              do (multiple-value-bind (symbol status)
                     (find-present-symbol client used-package name)
                   (unless (null status)
                     (return (values symbol :inherited))))
              finally (return (values nil nil))))))
