@node Purpose
@chapter Purpose

Parcl provides a complete implementation of the Common Lisp package
system.  It can be used as either an @emph{extrinsic} system in a Common
Lisp implementation that already has its own package system, or as an
@emph{intrinsic} system to provide a package system in a new Common
Lisp implementation. @xref{Implementations}.

The way the standard function obtains the value to pass is specific to
the client, which is why Parcl does not impose a particular technique.
One possibility for client code is to define the standard function as
a @emph{closure}, closing over the @code{client} object.  Another
possibility is to keep the @code{client} object as the value of a
special variable.
