\input texinfo

@settitle Parcl, an implementation of the Common Lisp package system.

@titlepage
@title Parcl documentation
@end titlepage

@contents

@node Top
@top Parcl

This document describes the implementation of Parcl.

@menu
* Purpose:: The reason for the existence of Parcl.
* Implementations:: Several different implementations.
* Index:: Complete index.
@end menu

@include chap-purpose.texi
@include chap-implementations.texi
@include chap-low-system.texi

@node Index
@unnumbered Index

@printindex cp

@bye
