\input texinfo

@include macros.texi
@include generated-version.texi

@settitle @sysname{}, an implementation of the Common Lisp package system.

@copying
This manual is for @sysname{} version @sysversion{}.

Copyright @copyright{} 2022 - 2025 s-expressionists
@end copying

@titlepage
@title @sysname{} documentation

@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Parcl

@insertcopying
@end ifnottex

@menu
* Introduction:: The reason for the existence of Parcl.
* Implementations:: Several different implementations.
* High Module:: Protocols for package system implementations.
* Middle Module:: Protocols for package system implementations.
* Low system:: Protocols for package system implementations.
* Index:: Concept Index.
@end menu

@include chapter-introduction.texi
@include chap-implementations.texi
@include chapter-high-module.texi
@include chapter-middle-module.texi
@include chap-low-system.texi

@node Index
@unnumbered Index

@printindex cp

@bye
