(cl:in-package #:parcl.middle)

(defmethod shadow ((client t) (package t) (name t))
  ;; TODO: the method for low-class uses the status - :internal-shadowing or :external-shadowing
  (multiple-value-bind (present-symbol export-status shadow-status)
      (low:symbol-entry client name package)
    (multiple-value-bind (symbol new-export-status)
        (if (null export-status)
            (values (low:make-symbol client name package) :internal) ; sets home package
            (values present-symbol                        export-status))
      (unless (and (eq new-export-status export-status) shadow-status)
        (setf (low:symbol-entry client name package)
              (values symbol new-export-status t)))
      symbol)))

#++ (defmethod parcl-low:shadow ((client low-class::client) package name)
  (let ((entry (parcl-low:name-to-entry client name (symbol-table package))))
    (if (null entry)
        (let* ((symbol (parcl-low:make-symbol client name package))
               (entry (make-entry symbol :internal-shadowing)))
          (add-entry client name entry package))
        (setf (entry-status entry)
              (case (entry-status entry)
                ((:internal :internal-shadowing) :internal-shadowing)
                (otherwise :external-shadowing)))))
  t)
